// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osrolxzvnurzisusvdvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zcm9seHp2bnVyemlzdXN2ZHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTUyNjUsImV4cCI6MjA2NjU3MTI2NX0.mPKzqkc-lc8w5Xi5aGvbv0I2zcl9adleENsG-mUs060";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);